/* date = December 22nd 2020 8:03 pm */

#ifndef WIN32_MAIN_H
#define WIN32_MAIN_H

//~ NOTE(Jai): Recursive macro definition only for 
// editor syntax highlighting
#define DWORD DWORD
#define FILETIME FILETIME
#define HMODULE HMODULE
#define HANDLE HANDLE
#define BITMAPINFO BITMAPINFO
#define HDC HDC
#define LARGE_INTEGER LARGE_INTEGER
#define XINPUT_STATE XINPUT_STATE
#define LONG LONG
#define SHORT SHORT
#define LPVOID LPVOID
#define HINSTANCE HINSTANCE
#define PSTR PSTR
#define HRESULT HRESULT
#define LPCGUID LPCGUID
#define LPUNKNOWN LPUNKNOWN
#define XINPUT_VIBRATION XINPUT_VIBRATION
#define WIN32_FIND_DATAA WIN32_FIND_DATAA
#define WIN32_FILE_ATTRIBUTE_DATA WIN32_FILE_ATTRIBUTE_DATA
#define LPDIRECTSOUNDBUFFER LPDIRECTSOUNDBUFFER
#define DSBUFFERDESC DSBUFFERDESC
#define WAVEFORMATEX WAVEFORMATEX
#define LPDIRECTSOUND LPDIRECTSOUND
#define MSG MSG
#define HCURSOR HCURSOR
#define PAINTSTRUCT PAINTSTRUCT
#define MONITORINFO MONITORINFO
#define LPARAM LPARAM
#define WINDOWPLACEMENT WINDOWPLACEMENT
#define WPARAM WPARAM
#define UINT UINT
#define HWND HWND
#define LRESULT LRESULT
//~

#endif //WIN32_MAIN_H
